# syntax=docker/dockerfile:1
FROM python:3.8-slim
ADD /app /code
WORKDIR /code
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
COPY app/requirements-av.txt /code/requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "sample.py"]
